### PR TITLE
Improve error on broken config

### LINKED ISSUE #83: Better error message on parsing config file
**Describe an issue**
If your `config.toml` file has a syntax and your run `spellcheck` with `--cfg` option there is such a error message.

```
Explicitly given config file does not exist
```

**To Reproduce**

Make a syntax mistake in toml e.g remove a `"` somewhere.

**Expected behavior**
Raise error with better message context for instance.

`Provided config file has a syntax issue`

**Fix**

Check error type here.

**Please complete the following information:**
 - System: Arch
 - Obtained: master

### PR DESCRIPTION
**Pull request by zhiburt**
Perhaps there is a better way to handle it.

closes #83

### CODE REVIEW

**Comment by zhiburt** [comment]
> Another (probably even better) would be returning a descriptive / "good" error and or providing a fn that automatically falls back, so this can be impl in impl Config rather than main.

Honestly didn't get this idea, but I hope now it's better?

```
[zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck --cfg README.md
Error: Syntax of a given config file(README.md) is broken

Caused by:
    unexpected character found: `!` at line 3 column 2
```

**Comment by drahnr** [comment]
> > Another (probably even better) would be returning a descriptive / "good" error and or providing a fn that automatically falls back, so this can be impl in impl Config rather than main.
> 
> Honestly didn't get this idea disappointed_relieved, but I hope now it's better?
> 
> ```
> [zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck --cfg README.md
> Error: Syntax of a given config file(README.md) is broken
> 
> Caused by:
>     unexpected character found: `!` at line 3 column 2
> ```

I completely missed your response, sorry for that.

Can you paste all 3 variants?

1. config with "good" toml
2. non existant toml file
3. config file exists, but contains invalid toml

All 3 of them should work flawlessly and yield an error description, which one case use to triage and address the issue.

**Comment by zhiburt** [comment]
* non existant toml file

```
[zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck --cfg README1.md
Error: No such file or directory (os error 2)

Caused by:
    Failed to open file README1.md
```

* good one

```
[zhiburt@zhiburt cargo-spellcheck]$ cargo spellcheck --cfg ~/.config/cargo_spellcheck/config.toml
error: spellcheck(Hunspell)
  --> /home/zhiburt/proj/cargo-spellcheck/src/checker/mod.rs:5
   |
 5 |  algorithms again and again, i.e. tokenization.
   |                                   ^^^^^^^^^^^^
   | - autoionization or ionization
   |
   |   Possible spelling mistake found.
   |

....
```

**Comment by drahnr** [comment]
Very nice!

**Pull request merged**
