### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by drahnr**
## What does this PR accomplish?

Bumps dependencies

 * 🪣 Misc

## 📜 Checklist

 * [x] Works on the `./demo` sub directory
 * [x] Test coverage is excellent and passes
 * [x] Documentation is thorough

### CODE REVIEW

**Comment by drahnr** [comment]
I'll take a look tomorrow~ish

**Comment by gilescope** [comment]
It's something to do with '.' properties and how that's interpreted. I have been upgrading every tool I come across to latest toml edit which does understand the latest format. It's not just you - I think we are the first to use this stuff.

**Comment by gilescope** [comment]
Here's an example PR of what we're trying to do: https://github.com/paritytech/polkadot/pull/6095

**Comment by gilescope** [comment]
This is the error I get if we ignore bash:

```
[2022-11-23T09:44:24Z DEBUG cargo_spellcheck::config::args] Using /home/gilescope/git/polkadot1/Cargo.toml manifest as anchor file
Error: 
   0: Failed to parse cargo manifest: /home/gilescope/git/polkadot1/Cargo.toml
   1: invalid type: map, expected a sequence for key `package.authors` at line 11 column 21
```

**Pull request merged**
