### PR TITLE
feat/test: add test cases for corner cases

### LINKED ISSUE #226: Citations written as "[number]" are spuriously detected as typos
**Describe the bug**

I have various pieces of information where I put a note of the form `[1]` inline or at the end to indicate the source being cited. Currently, each of these gets detected as a typo, making cargo-spellcheck completely impractical to run more often or automatically than "once before spinning a release".

**To Reproduce**

Steps to reproduce the behaviour:

1. Have a file containing a hyperlink with `[1]` or `[2]` or the like as the text in the documentation.
2. Run `cargo spellcheck check`

**Expected behavior**

A word that matches `\[\d+\]` after handling escapes should not be considered a typo.

**Screenshots**

```
error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:838
     |
 838 |    [\[1\]](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)
     |      ^^
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:847
     |
 847 |     [\[2\]](http://www.catb.org/esr/writings/taoup/html/ch10s05.html)
     |       ^^
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:848
     |
 848 |     [\[3\]](http://tldp.org/LDP/abs/html/standard-options.html)
     |       ^^
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:850
     |
 850 |     [\[4\]](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)
     |       ^^
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:870
     |
 870 |     [\[5\]](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file)
     |       ^^
     |   Possible spelling mistake found.

error: spellcheck(Hunspell)
    --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/src/path.rs:875
     |
 875 |       [\[6\]](https://www.boost.org/doc/libs/1_36_0/libs/filesystem/doc/portability_guide.htm)
     |         ^^
     |   Possible spelling mistake found.
```

**Please complete the following information:**
 - System: Kubuntu Linux 20.04.3 LTS
 - Obtained: cargo
 - Version: cargo-spellcheck 0.9.0

### LINKED ISSUE #227: Contents of doctests are not seen as code after a "#[doc = ...]" line
**Describe the bug**

In docstrings, a line using `#[doc = concat!(...)]` for substitution inside a doctest causes the following lines to be spell-checked as ordinary text.

This is a particularly big problem for functions generated using macros which use templated docstrings.

**To Reproduce**

Steps to reproduce the behaviour:

```rust
/// ```
/// use std::path::PathBuf as A;
#[doc = "// Hello"]
/// use std::path::PathBuf as B;
/// ```
fn main() {
    println!("Hello, world!");
}
```

1. Create a `main.rs` containing this minimual reproducer
2. Run `cargo spellcheck check`

**Expected behavior**

Neither `PathBuf` should be checked as an English word.

**Screenshots**

```
error: spellcheck(Hunspell)
  --> /home/ssokolow/src/rust-cli-boilerplate/cli_validators/temp/src/main.rs:4
   |
 4 |  use std::path::PathBuf as B;
   |                 ^^^^^^^
   | - Paths
   |
   |   Possible spelling mistake found.
```
**Please complete the following information:**
 - System: Kubuntu Linux 20.04.3 LTS
 - Obtained: cargo
 - Version: cargo-spellcheck 0.9.0

### PR DESCRIPTION
**Pull request by drahnr**
## What does this PR accomplish?

Introduces test cases for #226 and #227 and eventually fixes for both.

 * 🩹 Bug Fix

Closes #227, closes #226.

## 📜 Checklist

 * [x] Works on the `./demo` sub directory
 * [x] Test coverage is excellent and passes
 * [x] Documentation is thorough

### CODE REVIEW

**Comment by drahnr** [comment]
CC @ssokolow this is the WIP branch to address's the issues

**Comment by ssokolow** [comment]
Thanks. I'm winding down for bed, but I'll try to take a look at it tomorrow.

**Comment by drahnr** [comment]
Don't worry. Life is non-linear.

**Comment by ssokolow** [comment]
Sorry for the delay.  I just tried with git HEAD, but I can't say anything about its current behaviour because it looks like you accidentally made some kind of flood of internal debugging dumps the default output and I can't remember what to `grep` for to look for the *actual* output.

**Comment by drahnr** [comment]
Mea culpa

**Comment by drahnr** [comment]
Releasing `v0.9.2` right now to fix this

**Comment by drahnr** [comment]
Released `v0.9.2` and yanked `v0.9.1`.

**Pull request merged**
